version: '3.6'

services:
  mongo:
    ports:
      - "27018:27017"
  db:
    ports:
      - "5435:5432"
  server:
    ports:
      - "3002:3003"
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run dev
  front:
    ports:
      - "8002:5173"
    command:
      - /bin/bash
      - -c
      - |
          npm install
          npm run dev