version: '3'

services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mercant-db-data:/data/db
    working_dir: /usr/local/sampleCollections

  db:
    image: postgres
    networks:
      - mercant-site
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app
    volumes:
      - mercant-pg-data:/var/lib/postgresql/data

  server:
    image: node
    networks:
      - payless-network
      - mercant-site
    env_file:
      - back/.env
    working_dir: /usr/src/app
    volumes:
      - ./back:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
        npm install
        npm run build

  front:
    env_file:
      - front/.env
    networks:
      - mercant-site
    image: node:19.6
    working_dir: /usr/src/app
    volumes:
      - ./front:/usr/src/app
    command:
      - /bin/bash
      - -c
      - |
          npm install
          npm run build

volumes:
  mercant-db-data: {}
  mercant-pg-data: {}

networks:
  payless-network:
    external: true
  mercant-site:
    driver: bridge